name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          BRANCH: website
          FOLDER: docs-dist
          BUILD_SCRIPT: npm install && npm run docs:build
